// Standard 66-book order matching the bundled JSON datasets (gn, ex, lv, ... re)
// Each entry: [abbrev-in-dataset, Full Name, ...aliases used for voice/text matching]
module.exports = [
  ['gn', 'Genesis', 'gen'],
  ['ex', 'Exodus', 'exo'],
  ['lv', 'Leviticus', 'lev'],
  ['nm', 'Numbers', 'num'],
  ['dt', 'Deuteronomy', 'deut', 'deu'],
  ['js', 'Joshua', 'josh'],
  ['jud', 'Judges', 'jdg'],
  ['rt', 'Ruth'],
  ['1sm', '1 Samuel', 'first samuel', '1 sam', 'i samuel'],
  ['2sm', '2 Samuel', 'second samuel', '2 sam', 'ii samuel'],
  ['1kgs', '1 Kings', 'first kings', 'i kings'],
  ['2kgs', '2 Kings', 'second kings', 'ii kings'],
  ['1ch', '1 Chronicles', 'first chronicles', 'i chronicles'],
  ['2ch', '2 Chronicles', 'second chronicles', 'ii chronicles'],
  ['ezr', 'Ezra'],
  ['ne', 'Nehemiah', 'neh'],
  ['et', 'Esther', 'esth'],
  ['job', 'Job'],
  ['ps', 'Psalms', 'psalm', 'psa'],
  ['prv', 'Proverbs', 'prov'],
  ['ec', 'Ecclesiastes', 'eccl', 'eccles'],
  ['so', 'Song of Solomon', 'song of songs', 'canticles'],
  ['is', 'Isaiah', 'isa'],
  ['jr', 'Jeremiah', 'jer'],
  ['lm', 'Lamentations', 'lam'],
  ['ez', 'Ezekiel', 'ezek'],
  ['dn', 'Daniel', 'dan'],
  ['ho', 'Hosea', 'hos'],
  ['jl', 'Joel'],
  ['am', 'Amos'],
  ['ob', 'Obadiah', 'obad'],
  ['jn', 'Jonah'],
  ['mi', 'Micah', 'mic'],
  ['na', 'Nahum'],
  ['hk', 'Habakkuk', 'hab'],
  ['zp', 'Zephaniah', 'zeph'],
  ['hg', 'Haggai', 'hag'],
  ['zc', 'Zechariah', 'zech'],
  ['ml', 'Malachi', 'mal'],
  ['mt', 'Matthew', 'matt'],
  ['mk', 'Mark'],
  ['lk', 'Luke'],
  ['jo', 'John'],
  ['act', 'Acts'],
  ['rm', 'Romans', 'rom'],
  ['1co', '1 Corinthians', 'first corinthians', 'i corinthians', '1 cor'],
  ['2co', '2 Corinthians', 'second corinthians', 'ii corinthians', '2 cor'],
  ['gl', 'Galatians', 'gal'],
  ['eph', 'Ephesians'],
  ['ph', 'Philippians', 'phil'],
  ['cl', 'Colossians', 'col'],
  ['1ts', '1 Thessalonians', 'first thessalonians', 'i thessalonians'],
  ['2ts', '2 Thessalonians', 'second thessalonians', 'ii thessalonians'],
  ['1tm', '1 Timothy', 'first timothy', 'i timothy'],
  ['2tm', '2 Timothy', 'second timothy', 'ii timothy'],
  ['tt', 'Titus'],
  ['phm', 'Philemon'],
  ['hb', 'Hebrews', 'heb'],
  ['jm', 'James', 'jas'],
  ['1pe', '1 Peter', 'first peter', 'i peter'],
  ['2pe', '2 Peter', 'second peter', 'ii peter'],
  ['1jo', '1 John', 'first john', 'i john'],
  ['2jo', '2 John', 'second john', 'ii john'],
  ['3jo', '3 John', 'third john', 'iii john'],
  ['jd', 'Jude'],
  ['re', 'Revelation', 'revelations', 'rev', 'apocalypse'],
];
